import Head from "next/head";
import Header from "../components/Header";
import Nav from "../components/Nav";
export default function Home() {
  return (
    <div>
      <Head>
        <title>FilmBaz App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/movie-roll.png" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
        <link
          href="https://fonts.googleapis.com/css2?family=Poppins:wght@100;200;300;400;500;600&display=swap"
          rel="stylesheet"
        ></link>
      </Head>
      <Header />
      <Nav />
    </div>
  );
}
