import Head from "next/head";
import Header from "../components/Header";
import Nav from "../components/Nav";
import Results from "../components/Results";
import requests from "../utils/requests";
export default function Home({ results }) {
  console.log(results);
  return (
    <div>
      <Head>
        <title>FilmBaz 2.0</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/movie-roll.png" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
        <link
          href="https://fonts.googleapis.com/css2?family=Poppins:wght@100;200;300;400;500;600&display=swap"
          rel="stylesheet"
        ></link>
      </Head>
      <Header />
      <Nav />
      <Results results={results} />
    </div>
  );
}
export const getServerSideProps = async (context) => {
  const genre = context.query.genre;
  console.log(context.query.genre);
  const request = await fetch(
    `https://api.themoviedb.org/3${
      requests[genre]?.url || requests.fetchTrending.url
    }`
  ).then((res) => res.json());

  return {
    props: {
      results: request.results,
    },
  };
};
